services:
  mikado:
    image: anssi/fcsc2025-reverse-mikado:latest
    environment:
      - HOOS_CTF_EMAIL=${HOOS_CTF_EMAIL:-}
      - HOOS_CTF_USERNAME=${HOOS_CTF_USERNAME:-}
      - LANGUAGE=${LANGUAGE:-fr}
    labels:
      ho.ctf.cyrhades: "challenge"
    ports:
      - ${PORT}:4000
